feat: updating ci to check if tests are broken and cancel the deploy

diff --git a/.github/workflows/running-tests.yml b/.github/workflows/running-tests.yml
--- a/.github/workflows/running-tests.yml
+++ b/.github/workflows/running-tests.yml
@@ -29,5 +29,12 @@ jobs:
       - name: Running checkstyle
         run: mvn checkstyle:check
 
-      - name: Run tests
+      - name: Running tests
         run: mvn test
+
+      - name: Verify test status
+        run: |
+          if [ ${{ job.status }} == 'failure' ]; then
+            echo "Tests failed. Deployment to Railway canceled."
+            exit 1
+          fi
